# Generated by Django 4.0.5 on 2022-08-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0002_blood_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood',
            old_name='Blood_Type',
            new_name='blood_Type',
        ),
        migrations.RenameField(
            model_name='blood',
            old_name='Hospital',
            new_name='hospital',
        ),
    ]
