# Generated by Django 4.0.5 on 2022-09-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamii', '0003_rename_blood_type_blood_blood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools', models.CharField(max_length=200)),
                ('orphanages', models.CharField(max_length=200)),
                ('society', models.CharField(max_length=200)),
                ('hospitals', models.CharField(max_length=200)),
                ('prison', models.CharField(max_length=200)),
                ('refugees', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(max_length=200)),
                ('upload_image', models.ImageField(blank=True, upload_to='image/')),
                ('donate_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamii.donateto')),
            ],
        ),
    ]
